package nl.sison.xmpp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BUDDY_ENTITY.
 */
public class BuddyEntity {

    private Long id;
    /** Not-null value. */
    private String partial_jid;
    private String last_seen_resource;
    private String nickname;
    private String presence_status;
    private String presence_mode;
    private String presence_type;
    private java.util.Date last_chat_date;
    private java.util.Date last_seen_online_date;
    private Boolean isAvailable;
    private Boolean isAway;

    public BuddyEntity() {
    }

    public BuddyEntity(Long id) {
        this.id = id;
    }

    public BuddyEntity(Long id, String partial_jid, String last_seen_resource, String nickname, String presence_status, String presence_mode, String presence_type, java.util.Date last_chat_date, java.util.Date last_seen_online_date, Boolean isAvailable, Boolean isAway) {
        this.id = id;
        this.partial_jid = partial_jid;
        this.last_seen_resource = last_seen_resource;
        this.nickname = nickname;
        this.presence_status = presence_status;
        this.presence_mode = presence_mode;
        this.presence_type = presence_type;
        this.last_chat_date = last_chat_date;
        this.last_seen_online_date = last_seen_online_date;
        this.isAvailable = isAvailable;
        this.isAway = isAway;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPartial_jid() {
        return partial_jid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPartial_jid(String partial_jid) {
        this.partial_jid = partial_jid;
    }

    public String getLast_seen_resource() {
        return last_seen_resource;
    }

    public void setLast_seen_resource(String last_seen_resource) {
        this.last_seen_resource = last_seen_resource;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getPresence_status() {
        return presence_status;
    }

    public void setPresence_status(String presence_status) {
        this.presence_status = presence_status;
    }

    public String getPresence_mode() {
        return presence_mode;
    }

    public void setPresence_mode(String presence_mode) {
        this.presence_mode = presence_mode;
    }

    public String getPresence_type() {
        return presence_type;
    }

    public void setPresence_type(String presence_type) {
        this.presence_type = presence_type;
    }

    public java.util.Date getLast_chat_date() {
        return last_chat_date;
    }

    public void setLast_chat_date(java.util.Date last_chat_date) {
        this.last_chat_date = last_chat_date;
    }

    public java.util.Date getLast_seen_online_date() {
        return last_seen_online_date;
    }

    public void setLast_seen_online_date(java.util.Date last_seen_online_date) {
        this.last_seen_online_date = last_seen_online_date;
    }

    public Boolean getIsAvailable() {
        return isAvailable;
    }

    public void setIsAvailable(Boolean isAvailable) {
        this.isAvailable = isAvailable;
    }

    public Boolean getIsAway() {
        return isAway;
    }

    public void setIsAway(Boolean isAway) {
        this.isAway = isAway;
    }

}
