package nl.sison.xmpp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONNECTION_CONFIGURATION_ENTITY.
 */
public class ConnectionConfigurationEntity {

    private Long id;
    /** Not-null value. */
    private String label;
    /** Not-null value. */
    private String port;
    /** Not-null value. */
    private String server;
    private String domain;
    /** Not-null value. */
    private String username;
    /** Not-null value. */
    private String password;
    /** Not-null value. */
    private String resource;
    private boolean encrypted;
    private boolean compressed;
    private boolean saslauthenticated;
    private int connection_success;
    private Boolean vibrate;

    public ConnectionConfigurationEntity() {
    }

    public ConnectionConfigurationEntity(Long id) {
        this.id = id;
    }

    public ConnectionConfigurationEntity(Long id, String label, String port, String server, String domain, String username, String password, String resource, boolean encrypted, boolean compressed, boolean saslauthenticated, int connection_success, Boolean vibrate) {
        this.id = id;
        this.label = label;
        this.port = port;
        this.server = server;
        this.domain = domain;
        this.username = username;
        this.password = password;
        this.resource = resource;
        this.encrypted = encrypted;
        this.compressed = compressed;
        this.saslauthenticated = saslauthenticated;
        this.connection_success = connection_success;
        this.vibrate = vibrate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLabel() {
        return label;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLabel(String label) {
        this.label = label;
    }

    /** Not-null value. */
    public String getPort() {
        return port;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPort(String port) {
        this.port = port;
    }

    /** Not-null value. */
    public String getServer() {
        return server;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setServer(String server) {
        this.server = server;
    }

    public String getDomain() {
        return domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    /** Not-null value. */
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String username) {
        this.username = username;
    }

    /** Not-null value. */
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String password) {
        this.password = password;
    }

    /** Not-null value. */
    public String getResource() {
        return resource;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setResource(String resource) {
        this.resource = resource;
    }

    public boolean getEncrypted() {
        return encrypted;
    }

    public void setEncrypted(boolean encrypted) {
        this.encrypted = encrypted;
    }

    public boolean getCompressed() {
        return compressed;
    }

    public void setCompressed(boolean compressed) {
        this.compressed = compressed;
    }

    public boolean getSaslauthenticated() {
        return saslauthenticated;
    }

    public void setSaslauthenticated(boolean saslauthenticated) {
        this.saslauthenticated = saslauthenticated;
    }

    public int getConnection_success() {
        return connection_success;
    }

    public void setConnection_success(int connection_success) {
        this.connection_success = connection_success;
    }

    public Boolean getVibrate() {
        return vibrate;
    }

    public void setVibrate(Boolean vibrate) {
        this.vibrate = vibrate;
    }

}
