package nl.sison.xmpp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE_ENTITY.
 */
public class MessageEntity {

    private Long id;
    /** Not-null value. */
    private String sender_jid;
    /** Not-null value. */
    private String receiver_jid;
    /** Not-null value. */
    private String content;
    /** Not-null value. */
    private java.util.Date received_date;
    private Boolean delivered;

    public MessageEntity() {
    }

    public MessageEntity(Long id) {
        this.id = id;
    }

    public MessageEntity(Long id, String sender_jid, String receiver_jid, String content, java.util.Date received_date, Boolean delivered) {
        this.id = id;
        this.sender_jid = sender_jid;
        this.receiver_jid = receiver_jid;
        this.content = content;
        this.received_date = received_date;
        this.delivered = delivered;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSender_jid() {
        return sender_jid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSender_jid(String sender_jid) {
        this.sender_jid = sender_jid;
    }

    /** Not-null value. */
    public String getReceiver_jid() {
        return receiver_jid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setReceiver_jid(String receiver_jid) {
        this.receiver_jid = receiver_jid;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    /** Not-null value. */
    public java.util.Date getReceived_date() {
        return received_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setReceived_date(java.util.Date received_date) {
        this.received_date = received_date;
    }

    public Boolean getDelivered() {
        return delivered;
    }

    public void setDelivered(Boolean delivered) {
        this.delivered = delivered;
    }

}
