package nl.sison.xmpp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import nl.sison.xmpp.dao.MessageEntity;
import nl.sison.xmpp.dao.BuddyEntity;
import nl.sison.xmpp.dao.ConnectionConfigurationEntity;

import nl.sison.xmpp.dao.MessageEntityDao;
import nl.sison.xmpp.dao.BuddyEntityDao;
import nl.sison.xmpp.dao.ConnectionConfigurationEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageEntityDaoConfig;
    private final DaoConfig buddyEntityDaoConfig;
    private final DaoConfig connectionConfigurationEntityDaoConfig;

    private final MessageEntityDao messageEntityDao;
    private final BuddyEntityDao buddyEntityDao;
    private final ConnectionConfigurationEntityDao connectionConfigurationEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageEntityDaoConfig = daoConfigMap.get(MessageEntityDao.class).clone();
        messageEntityDaoConfig.initIdentityScope(type);

        buddyEntityDaoConfig = daoConfigMap.get(BuddyEntityDao.class).clone();
        buddyEntityDaoConfig.initIdentityScope(type);

        connectionConfigurationEntityDaoConfig = daoConfigMap.get(ConnectionConfigurationEntityDao.class).clone();
        connectionConfigurationEntityDaoConfig.initIdentityScope(type);

        messageEntityDao = new MessageEntityDao(messageEntityDaoConfig, this);
        buddyEntityDao = new BuddyEntityDao(buddyEntityDaoConfig, this);
        connectionConfigurationEntityDao = new ConnectionConfigurationEntityDao(connectionConfigurationEntityDaoConfig, this);

        registerDao(MessageEntity.class, messageEntityDao);
        registerDao(BuddyEntity.class, buddyEntityDao);
        registerDao(ConnectionConfigurationEntity.class, connectionConfigurationEntityDao);
    }
    
    public void clear() {
        messageEntityDaoConfig.getIdentityScope().clear();
        buddyEntityDaoConfig.getIdentityScope().clear();
        connectionConfigurationEntityDaoConfig.getIdentityScope().clear();
    }

    public MessageEntityDao getMessageEntityDao() {
        return messageEntityDao;
    }

    public BuddyEntityDao getBuddyEntityDao() {
        return buddyEntityDao;
    }

    public ConnectionConfigurationEntityDao getConnectionConfigurationEntityDao() {
        return connectionConfigurationEntityDao;
    }

}
