package nl.antonius.zorgdashboardwidget.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BUDDY_ENTITY.
 */
public class BuddyEntity {

    private Long id;
    /** Not-null value. */
    private String partial_jid;
    /** Not-null value. */
    private String resource;
    /** Not-null value. */
    private String nickname;
    /** Not-null value. */
    private String presence;
    /** Not-null value. */
    private String custom_away_string;
    private java.util.Date last_seen_date;

    public BuddyEntity() {
    }

    public BuddyEntity(Long id, String partial_jid, String resource) {
        this.id = id;
        this.partial_jid = partial_jid;
        this.resource = resource;
    }

    public BuddyEntity(Long id, String partial_jid, String resource, String nickname, String presence, String custom_away_string, java.util.Date last_seen_date) {
        this.id = id;
        this.partial_jid = partial_jid;
        this.resource = resource;
        this.nickname = nickname;
        this.presence = presence;
        this.custom_away_string = custom_away_string;
        this.last_seen_date = last_seen_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPartial_jid() {
        return partial_jid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPartial_jid(String partial_jid) {
        this.partial_jid = partial_jid;
    }

    /** Not-null value. */
    public String getResource() {
        return resource;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setResource(String resource) {
        this.resource = resource;
    }

    /** Not-null value. */
    public String getNickname() {
        return nickname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /** Not-null value. */
    public String getPresence() {
        return presence;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPresence(String presence) {
        this.presence = presence;
    }

    /** Not-null value. */
    public String getCustom_away_string() {
        return custom_away_string;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCustom_away_string(String custom_away_string) {
        this.custom_away_string = custom_away_string;
    }

    public java.util.Date getLast_seen_date() {
        return last_seen_date;
    }

    public void setLast_seen_date(java.util.Date last_seen_date) {
        this.last_seen_date = last_seen_date;
    }

}
