package nl.antonius.zorgdashboardwidget.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import nl.antonius.zorgdashboardwidget.dao.MessageEntity;
import nl.antonius.zorgdashboardwidget.dao.BuddyEntity;
import nl.antonius.zorgdashboardwidget.dao.SettingsEntity;

import nl.antonius.zorgdashboardwidget.dao.MessageEntityDao;
import nl.antonius.zorgdashboardwidget.dao.BuddyEntityDao;
import nl.antonius.zorgdashboardwidget.dao.SettingsEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageEntityDaoConfig;
    private final DaoConfig buddyEntityDaoConfig;
    private final DaoConfig settingsEntityDaoConfig;

    private final MessageEntityDao messageEntityDao;
    private final BuddyEntityDao buddyEntityDao;
    private final SettingsEntityDao settingsEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageEntityDaoConfig = daoConfigMap.get(MessageEntityDao.class).clone();
        messageEntityDaoConfig.initIdentityScope(type);

        buddyEntityDaoConfig = daoConfigMap.get(BuddyEntityDao.class).clone();
        buddyEntityDaoConfig.initIdentityScope(type);

        settingsEntityDaoConfig = daoConfigMap.get(SettingsEntityDao.class).clone();
        settingsEntityDaoConfig.initIdentityScope(type);

        messageEntityDao = new MessageEntityDao(messageEntityDaoConfig, this);
        buddyEntityDao = new BuddyEntityDao(buddyEntityDaoConfig, this);
        settingsEntityDao = new SettingsEntityDao(settingsEntityDaoConfig, this);

        registerDao(MessageEntity.class, messageEntityDao);
        registerDao(BuddyEntity.class, buddyEntityDao);
        registerDao(SettingsEntity.class, settingsEntityDao);
    }
    
    public void clear() {
        messageEntityDaoConfig.getIdentityScope().clear();
        buddyEntityDaoConfig.getIdentityScope().clear();
        settingsEntityDaoConfig.getIdentityScope().clear();
    }

    public MessageEntityDao getMessageEntityDao() {
        return messageEntityDao;
    }

    public BuddyEntityDao getBuddyEntityDao() {
        return buddyEntityDao;
    }

    public SettingsEntityDao getSettingsEntityDao() {
        return settingsEntityDao;
    }

}
