package nl.antonius.zorgdashboardwidget.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SETTINGS_ENTITY.
 */
public class SettingsEntity {

    private Long id;
    private String xmpp_port;
    private String xmpp_server;
    /** Not-null value. */
    private String xmpp_username;
    /** Not-null value. */
    private String xmpp_password;
    /** Not-null value. */
    private String xmpp_jid;
    private String xmpp_resource;

    public SettingsEntity() {
    }

    public SettingsEntity(Long id) {
        this.id = id;
    }

    public SettingsEntity(Long id, String xmpp_port, String xmpp_server, String xmpp_username, String xmpp_password, String xmpp_jid, String xmpp_resource) {
        this.id = id;
        this.xmpp_port = xmpp_port;
        this.xmpp_server = xmpp_server;
        this.xmpp_username = xmpp_username;
        this.xmpp_password = xmpp_password;
        this.xmpp_jid = xmpp_jid;
        this.xmpp_resource = xmpp_resource;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getXmpp_port() {
        return xmpp_port;
    }

    public void setXmpp_port(String xmpp_port) {
        this.xmpp_port = xmpp_port;
    }

    public String getXmpp_server() {
        return xmpp_server;
    }

    public void setXmpp_server(String xmpp_server) {
        this.xmpp_server = xmpp_server;
    }

    /** Not-null value. */
    public String getXmpp_username() {
        return xmpp_username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setXmpp_username(String xmpp_username) {
        this.xmpp_username = xmpp_username;
    }

    /** Not-null value. */
    public String getXmpp_password() {
        return xmpp_password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setXmpp_password(String xmpp_password) {
        this.xmpp_password = xmpp_password;
    }

    /** Not-null value. */
    public String getXmpp_jid() {
        return xmpp_jid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setXmpp_jid(String xmpp_jid) {
        this.xmpp_jid = xmpp_jid;
    }

    public String getXmpp_resource() {
        return xmpp_resource;
    }

    public void setXmpp_resource(String xmpp_resource) {
        this.xmpp_resource = xmpp_resource;
    }

}
